apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJjSFp0WVhOdWVUcG5hSEJmZWxaVVJHMVBOV3hDYTJWTmEwNWliMll3WjFKR1dGSk9kRTQyWjFsc01XeERNRUZ6In19fQ==
type: kubernetes.io/dockerconfigjson
